### ISSUE TITLE
Event is not defined ReferenceError: Event is not defined

### ISSUE THREAD

**Issue by CP-Ram** [anasAsh/ngx-scroll-event#15]
I have angular7 cli project and when trying to build with universal getting the following Error on console

Event is not defined
ReferenceError: Event is not defined
    at D:\app2019\dev\customerapp\app\node_modules\ngx-scroll-event\src\scroll.directive.js:59:42
    at Object.<anonymous> (D:\app2019\dev\customerapp\app\node_modules\ngx-scroll-event\src\scroll.directive.js:75:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\app2019\dev\customerapp\app\node_modules\ngx-scroll-event\src\scroll.module.js:11:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)

and i am using "ngx-scroll-event": "^1.0.8" version in package.json file.

any help to solve above error.

**Comment by matbalazsi** [comment]
Same here. Any updates on Universal?
